/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaServicio;

import Ventanas.*;

/**
 *
 * @author Usuario
 */
public class ServisMaster extends javax.swing.JFrame {

    /**
     * Creates new form ServisMaster
     */
    public ServisMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BusquedaPrducto = new javax.swing.JButton();
        txtescaner = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        AddMore = new javax.swing.JMenuItem();
        UsuarioNuevo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 649));
        setMinimumSize(new java.awt.Dimension(950, 649));
        setPreferredSize(new java.awt.Dimension(950, 700));
        getContentPane().setLayout(null);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Codigo del producto", "Nombre del producto", "Precio"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 170, 970, 390);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido Administrador Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 870, 90);

        BusquedaPrducto.setText("Escanear o Busqueda ID");
        BusquedaPrducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusquedaPrductoMouseClicked(evt);
            }
        });
        getContentPane().add(BusquedaPrducto);
        BusquedaPrducto.setBounds(499, 130, 171, 25);
        getContentPane().add(txtescaner);
        txtescaner.setBounds(690, 130, 200, 22);

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(10, 580, 59, 25);
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 970, 630);

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Agregar productos nuevos");
        jMenu1.add(jMenuItem1);

        AddMore.setText("Agregar más productos");
        AddMore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMoreMouseClicked(evt);
            }
        });
        jMenu1.add(AddMore);

        UsuarioNuevo.setText("Crear usuario");
        UsuarioNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioNuevoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuarioNuevoMousePressed(evt);
            }
        });
        jMenu1.add(UsuarioNuevo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusquedaPrductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusquedaPrductoMouseClicked
        // TODO add your handling code here:
        if (!txtescaner.getText().equals("")){
           
            System.out.println("Codigo:  " + txtescaner.getText());
            txtescaner.setText("");
        }
        else{
            System.out.println("No ah ingresado el codigo para buscar el articulo");
        }
    }//GEN-LAST:event_BusquedaPrductoMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginUser Login = new LoginUser();
        Login.setVisible(true);
    }//GEN-LAST:event_SalirMouseClicked

    private void UsuarioNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioNuevoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UsuarioNuevoMouseClicked

    private void AddMoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMoreMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AddMoreMouseClicked

    private void UsuarioNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioNuevoMousePressed
        // TODO add your handling code here:
        this.dispose();
        CrearUser user;
        user = new CrearUser();
        user.regreso = 1;
        user.setVisible(true);
    }//GEN-LAST:event_UsuarioNuevoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServisMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServisMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServisMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServisMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServisMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddMore;
    private javax.swing.JButton BusquedaPrducto;
    private javax.swing.JButton Salir;
    private javax.swing.JTable Tabla;
    private javax.swing.JMenuItem UsuarioNuevo;
    public static javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtescaner;
    // End of variables declaration//GEN-END:variables
}
