/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaServicio;

import Ventanas.*;

/**
 *
 * @author Usuario
 */
public class ServicioUser extends javax.swing.JFrame {

    /**
     * Creates new form ServicioUser
     */
    public ServicioUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BuscarID = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Total = new javax.swing.JButton();
        NameUser = new javax.swing.JLabel();
        txtescaner = new javax.swing.JTextField();
        BusquedaID = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CerraSesion = new javax.swing.JMenuItem();

        jLabel1.setText("Buscar por ID");

        BuscarID.setText("Buscar por ID");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 649));
        setMinimumSize(new java.awt.Dimension(1024, 649));
        getContentPane().setLayout(null);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Codigo del producto", "Nombre del producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 180, 1020, 292);

        Total.setText("Precio total");
        Total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalMouseClicked(evt);
            }
        });
        getContentPane().add(Total);
        Total.setBounds(850, 490, 129, 42);

        NameUser.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        NameUser.setText("Bienvenido Usuario");
        getContentPane().add(NameUser);
        NameUser.setBounds(280, 40, 450, 51);

        txtescaner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtescanerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtescanerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtescanerKeyTyped(evt);
            }
        });
        getContentPane().add(txtescaner);
        txtescaner.setBounds(820, 140, 155, 22);

        BusquedaID.setText("Escanear o Busqueda ID");
        BusquedaID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusquedaIDMouseClicked(evt);
            }
        });
        getContentPane().add(BusquedaID);
        BusquedaID.setBounds(630, 140, 171, 25);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1060, 570);

        jMenu1.setText("Opciones");

        CerraSesion.setText("Cerrar sesión");
        CerraSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerraSesionMouseClicked(evt);
            }
        });
        jMenu1.add(CerraSesion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtescanerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtescanerKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtescanerKeyTyped

    private void txtescanerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtescanerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtescanerKeyPressed

    private void txtescanerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtescanerKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtescanerKeyReleased

    private void BusquedaIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusquedaIDMouseClicked
        // TODO add your handling code here:
        if (!txtescaner.getText().equals("")){
           
            System.out.println("Codigo:  " + txtescaner.getText());
            txtescaner.setText("");
        }
        else{
            System.out.println("No ah ingresado el codigo para buscar el articulo");
        }
    }//GEN-LAST:event_BusquedaIDMouseClicked

    private void CerraSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerraSesionMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginUser Login = new LoginUser();
        Login.setVisible(true);
    }//GEN-LAST:event_CerraSesionMouseClicked

    private void TotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TotalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicioUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicioUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicioUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicioUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicioUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarID;
    private javax.swing.JButton BusquedaID;
    private javax.swing.JMenuItem CerraSesion;
    private javax.swing.JLabel NameUser;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton Total;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtescaner;
    // End of variables declaration//GEN-END:variables
}
