/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import puntoventa.PuntoVenta;
import javax.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Milh
 */
public class CrearUser extends javax.swing.JFrame {
    PuntoVenta con;
    /**
     * Creates new form CrearUser
     */
    public CrearUser() {
        initComponents();
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        NomU = new javax.swing.JTextField();
        Contraseña = new javax.swing.JLabel();
        ContraU = new javax.swing.JPasswordField();
        ConContraseña = new javax.swing.JLabel();
        ConContraU = new javax.swing.JPasswordField();
        Codigo = new javax.swing.JLabel();
        CodigoU = new javax.swing.JPasswordField();
        Crear = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));
        setSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Crear Usuarios");
        getContentPane().add(Titulo);
        Titulo.setBounds(80, 10, 260, 100);

        Nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre:");
        getContentPane().add(Nombre);
        Nombre.setBounds(20, 130, 90, 30);

        NomU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(NomU);
        NomU.setBounds(200, 130, 150, 28);

        Contraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("Contraseña:");
        getContentPane().add(Contraseña);
        Contraseña.setBounds(20, 180, 100, 22);

        ContraU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(ContraU);
        ContraU.setBounds(200, 180, 150, 28);

        ConContraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConContraseña.setForeground(new java.awt.Color(255, 255, 255));
        ConContraseña.setText("Confirmar Contraseña:");
        getContentPane().add(ConContraseña);
        ConContraseña.setBounds(20, 230, 177, 22);

        ConContraU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(ConContraU);
        ConContraU.setBounds(200, 230, 150, 28);

        Codigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Codigo.setForeground(new java.awt.Color(255, 255, 255));
        Codigo.setText("Codigo Administrador:");
        getContentPane().add(Codigo);
        Codigo.setBounds(20, 280, 180, 22);

        CodigoU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(CodigoU);
        CodigoU.setBounds(200, 280, 150, 28);

        Crear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Crear.setText("Crear");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        getContentPane().add(Crear);
        Crear.setBounds(160, 340, 73, 31);

        Fondo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fon.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(400, 500));
        Fondo.setMinimumSize(new java.awt.Dimension(400, 500));
        Fondo.setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().add(Fondo);
        Fondo.setBounds(-16, -16, 420, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        // TODO add your handling code here:
        con = new PuntoVenta();
        Connection reg = con.conexion();
        if(!NomU.getText().equals("") && !ContraU.getText().equals("") && ContraU.getText().equals(ConContraU.getText())){
            try{
                PreparedStatement pst = reg.prepareStatement("INSERT INTO usuarios(Nombre, Contraseña, Tipo) VALUES(?, ?, ?)");
                pst.setString(1, NomU.getText());
                pst.setString(2, ContraU.getText());
                if(!CodigoU.getText().equals("")){
                    pst.setInt(3, 1);
                }
                else{
                    pst.setInt(3, 2);
                }
                pst.executeUpdate();
                }catch(SQLException e){           
                }
        }else{
            if(NomU.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por Favor llene el campo de Nombre");
            }
            else if(ContraU.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por Favor llene el campo de Contraseña");
                
            }else if(!ContraU.getText().equals(ConContraU.getText())){
                JOptionPane.showMessageDialog(null, "Verifique su Contraseña si es correcta");
            }
        }
        NomU.setText("");
        ContraU.setText("");
        ConContraU.setText("");
        CodigoU.setText("");
    }//GEN-LAST:event_CrearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codigo;
    private javax.swing.JPasswordField CodigoU;
    private javax.swing.JPasswordField ConContraU;
    private javax.swing.JLabel ConContraseña;
    private javax.swing.JPasswordField ContraU;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JButton Crear;
    public static javax.swing.JLabel Fondo;
    private javax.swing.JTextField NomU;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables

    private LoginUser LoginUser() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
