/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import puntoventa.PuntoVenta;
import javax.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Milh
 */
public class CrearUser extends javax.swing.JFrame {
    PuntoVenta con;
    /**
     * Creates new form CrearUser
     */
    public CrearUser() {
        initComponents();
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        NomU = new javax.swing.JTextField();
        Contraseña = new javax.swing.JLabel();
        ContraU = new javax.swing.JPasswordField();
        ConContraseña = new javax.swing.JLabel();
        ConContraU = new javax.swing.JPasswordField();
        Codigo = new javax.swing.JLabel();
        CodigoU = new javax.swing.JPasswordField();
        Crear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));
        setSize(new java.awt.Dimension(400, 500));

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 102, 102));
        Titulo.setText("Crear Usuarios");

        Nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nombre.setText("Nombre:");

        NomU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Contraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Contraseña.setText("Contraseña:");

        ContraU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ConContraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConContraseña.setText("Confirmar Contraseña:");

        ConContraU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Codigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Codigo.setText("Codigo Administrador:");

        CodigoU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Crear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Crear.setText("Crear");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(NomU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(ContraU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(ConContraseña)
                        .addGap(3, 3, 3)
                        .addComponent(ConContraU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(CodigoU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(Crear)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contraseña)
                    .addComponent(ContraU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConContraseña)
                    .addComponent(ConContraU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo)
                    .addComponent(CodigoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(Crear)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        // TODO add your handling code here:
        con = new PuntoVenta();
        Connection reg = con.conexion();
        if(!NomU.getText().equals("") && !ContraU.getText().equals("") && ContraU.getText().equals(ConContraU.getText())){
            try{
                PreparedStatement pst = reg.prepareStatement("INSERT INTO usuarios(Nombre, Contraseña, Tipo) VALUES(?, ?, ?)");
                pst.setString(1, NomU.getText());
                pst.setString(2, ContraU.getText());
                if(!CodigoU.getText().equals("")){
                    pst.setInt(3, 1);
                }
                else{
                    pst.setInt(3, 2);
                }
                pst.executeUpdate();
                }catch(SQLException e){           
                }
        }else{
            if(NomU.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por Favor llene el campo de Nombre");
            }
            else if(ContraU.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por Favor llene el campo de Contraseña");
                
            }else if(!ContraU.getText().equals(ConContraU.getText())){
                JOptionPane.showMessageDialog(null, "Verifique su Contraseña si es correcta");
            }
        }
        NomU.setText("");
        ContraU.setText("");
        ConContraU.setText("");
        CodigoU.setText("");
    }//GEN-LAST:event_CrearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codigo;
    private javax.swing.JPasswordField CodigoU;
    private javax.swing.JPasswordField ConContraU;
    private javax.swing.JLabel ConContraseña;
    private javax.swing.JPasswordField ContraU;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JButton Crear;
    private javax.swing.JTextField NomU;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables

    private LoginUser LoginUser() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
