/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import VentanaServicio.ServisMaster;
import puntoventa.PuntoVenta;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Milh
 */
public class LoginUser extends javax.swing.JFrame {
    PuntoVenta con;
    /**
     * Creates new form CrearUsuario
     */
    public LoginUser() {
        initComponents();
        
    }
//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreI = new javax.swing.JLabel();
        ContraseñaI = new javax.swing.JLabel();
        NombrI = new javax.swing.JTextField();
        ContraI = new javax.swing.JPasswordField();
        CrearI = new javax.swing.JButton();
        IniciarI = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        NombreI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreI.setText("Nombre:");

        ContraseñaI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ContraseñaI.setText("Contraseña:");

        NombrI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ContraI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CrearI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CrearI.setText("Crear Usuario");
        CrearI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearIMouseClicked(evt);
            }
        });

        IniciarI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IniciarI.setText("Iniciar Secion");
        IniciarI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarIMouseClicked(evt);
            }
        });

        imagen.setBackground(new java.awt.Color(255, 255, 255));
        imagen.setText("Jjjajajaja ACA IBA UNA IMAGEN XD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContraseñaI)
                            .addComponent(NombreI))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombrI, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(ContraI)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CrearI)
                        .addGap(18, 18, 18)
                        .addComponent(IniciarI)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreI)
                            .addComponent(NombrI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContraseñaI)
                            .addComponent(ContraI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CrearI)
                            .addComponent(IniciarI)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void CrearIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearIMouseClicked
        // TODO add your handling code here:
        this.dispose();
        CrearUser Crear = new CrearUser();
        Crear.regreso = 2;
        Crear.setVisible(true);
    }//GEN-LAST:event_CrearIMouseClicked

    private void IniciarIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarIMouseClicked
        // TODO add your handling code here:
       /* if(!NombrI.getText().equals("") && !ContraI.getText().equals("")){
            con = new PuntoVenta();
            ResultSet busqueda = con.executeSelect("SELECT Nombre, Contraseña, Tipo FROM usuarios");
            
            boolean userExists = false;
            boolean passCorrect = false;
            
            try {
                while(busqueda.next()) {
                    String nombre = busqueda.getString("Nombre");
                    String contrasenia = busqueda.getString("Contraseña");
                    String tipo = busqueda.getString("Tipo");
                    if(NombrI.getText().equals(nombre)) {
                        userExists = true;
                        if(ContraI.getText().equals(contrasenia)) {
                            passCorrect = true;
                            if(tipo.equals("1")){
                                dispose();
                                ServisMaster admin = new ServisMaster();
                                admin.setVisible(true);
                            }
                            else{
                                dispose();
                                ServicioUser cajero = new ServicioUser();
                                cajero.setVisible(true);
                            }
                            
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
       ServisMaster servis = new ServisMaster();
       servis.setVisible(true);
    }//GEN-LAST:event_IniciarIMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContraI;
    private javax.swing.JLabel ContraseñaI;
    private javax.swing.JButton CrearI;
    private javax.swing.JButton IniciarI;
    private javax.swing.JTextField NombrI;
    private javax.swing.JLabel NombreI;
    public static javax.swing.JLabel imagen;
    // End of variables declaration//GEN-END:variables
}
