/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import puntoventa.PuntoVenta;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Milh
 */
public class LoginUser extends javax.swing.JFrame {
    PuntoVenta con;
    int tipo;
    /**
     * Creates new form CrearUsuario
     */
    public LoginUser() {
        initComponents();
        ImageIcon imagen1=new ImageIcon(getClass().getResource("/Imagenes/UPC.png"));
        ImageIcon fondo1=new ImageIcon(imagen1.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(fondo1);
        
    }
//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreI = new javax.swing.JLabel();
        ContraseñaI = new javax.swing.JLabel();
        NombrI = new javax.swing.JTextField();
        ContraI = new javax.swing.JPasswordField();
        CrearI = new javax.swing.JButton();
        IniciarI = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        NombreI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreI.setText("Nombre:");

        ContraseñaI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ContraseñaI.setText("Contraseña:");

        NombrI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ContraI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CrearI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CrearI.setText("Crear Usuario");
        CrearI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearIMouseClicked(evt);
            }
        });

        IniciarI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IniciarI.setText("Iniciar Secion");
        IniciarI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarIMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NombreI)
                        .addGap(39, 39, 39)
                        .addComponent(NombrI, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContraseñaI)
                        .addGap(18, 18, 18)
                        .addComponent(ContraI, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CrearI)
                        .addGap(18, 18, 18)
                        .addComponent(IniciarI))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(NombreI))
                    .addComponent(NombrI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ContraseñaI))
                    .addComponent(ContraI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearI)
                    .addComponent(IniciarI)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void CrearIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearIMouseClicked
        // TODO add your handling code here:
        this.dispose();
        CrearUser Crear = new CrearUser();
        Crear.setVisible(true);
    }//GEN-LAST:event_CrearIMouseClicked

    private void IniciarIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarIMouseClicked
        // TODO add your handling code here:
        String pass;
        con = new PuntoVenta();
        if(!NombrI.getText().equals("") && !new String(ContraI.getPassword()).equals("")){
            
            pass=resultbusqueda(NombrI.getText());
            if(pass.equals(new String(ContraI.getPassword()))){
                if(tipo==1){
                    ServisMaster admin = new ServisMaster();
                    admin.setVisible(true);
                }
                if(tipo==2){
                    ServicioUser cajero = new ServicioUser();
                    cajero.setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Contraseñ Iconrrecta","Error Datos",JOptionPane.ERROR_MESSAGE);
            }
            boolean userExists = false;
            boolean passCorrect = false;
            
          
        }
    }//GEN-LAST:event_IniciarIMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContraI;
    private javax.swing.JLabel ContraseñaI;
    private javax.swing.JButton CrearI;
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton IniciarI;
    private javax.swing.JTextField NombrI;
    private javax.swing.JLabel NombreI;
    // End of variables declaration//GEN-END:variables

    private String resultbusqueda(String usuario) {
        PreparedStatement carrito;
        ResultSet busqueda;
        String password=null;
        String select="select Contraseña, Tipo FROM usuarios WHERE Nombre= ?";
            try{
             carrito=con.conexion().prepareStatement(select);
             carrito.setString(1,usuario);
             busqueda = carrito.executeQuery();
           
             if(busqueda.next()){
                 password=busqueda.getString(1);
                 tipo=busqueda.getInt(2);
             }
             
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Dato", JOptionPane.ERROR_MESSAGE);
            }
        return password;
    }
}
