/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import puntoventa.PuntoVenta;
import java.sql.*;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Milh
 */
public class LoginUser extends javax.swing.JFrame {
    PuntoVenta con;
    int tipo;
    /**
     * Creates new form CrearUsuario
     */
    public LoginUser() {
        initComponents();  
        this.setResizable(false);
    }
//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreI = new javax.swing.JLabel();
        ContraseñaI = new javax.swing.JLabel();
        NombrI = new javax.swing.JTextField();
        ContraI = new javax.swing.JPasswordField();
        CrearI = new javax.swing.JButton();
        IniciarI = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        NombreI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreI.setText("Nombre:");

        ContraseñaI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ContraseñaI.setText("Contraseña:");

        NombrI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ContraI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CrearI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CrearI.setText("Crear Usuario");
        CrearI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearIMouseClicked(evt);
            }
        });

        IniciarI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IniciarI.setText("Iniciar Secion");
        IniciarI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarIMouseClicked(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 102, 102));
        Titulo.setText("      Iniciar Sesion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContraseñaI)
                                    .addComponent(NombreI))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombrI, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContraI, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CrearI)
                        .addGap(58, 58, 58)
                        .addComponent(IniciarI)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombrI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ContraseñaI)
                    .addComponent(ContraI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearI)
                    .addComponent(IniciarI))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void CrearIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearIMouseClicked
        // TODO add your handling code here:
        this.dispose();
        CrearUser mostrar = new CrearUser();
        mostrar.regresar = 2;
        mostrar.setVisible(true);
    }//GEN-LAST:event_CrearIMouseClicked

    private void IniciarIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarIMouseClicked
        // TODO add your handling code here:
        String pass;
        con = new PuntoVenta();
        if(!NombrI.getText().equals("") && !new String(ContraI.getPassword()).equals("")){
            
            pass=resultbusqueda(NombrI.getText());
            if(pass.equals(new String(ContraI.getPassword()))){
                if(tipo==1){
                    Administrador admin = new Administrador();
                    admin.setVisible(true);
                    
                }
                if(tipo==2){
                    Cajero cajero = new Cajero();
                    DefaultTableModel mod= new DefaultTableModel();                   
                    cajero.setVisible(true);
                } 
            }else{
                JOptionPane.showMessageDialog(null,"Contraseña Inconrrecta","Error Datos",JOptionPane.ERROR_MESSAGE);
            }
            boolean userExists = false;
            boolean passCorrect = false;   
            this.dispose();
        }
        
        else {
            JOptionPane.showMessageDialog(null,"Falto llenar los campos", "Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_IniciarIMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContraI;
    private javax.swing.JLabel ContraseñaI;
    private javax.swing.JButton CrearI;
    private javax.swing.JButton IniciarI;
    private javax.swing.JTextField NombrI;
    private javax.swing.JLabel NombreI;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables

    private String resultbusqueda(String usuario) {
        PreparedStatement carrito;
        ResultSet busqueda;
        String password=null;
        String select="select Contraseña, Tipo FROM usuarios WHERE Nombre= ?";
            try{
             carrito=con.conexion().prepareStatement(select);
             carrito.setString(1,usuario);
             busqueda = carrito.executeQuery();
           
             if(busqueda.next()){
                 password=busqueda.getString(1);
                 tipo=busqueda.getInt(2);
             }
             
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Dato", JOptionPane.ERROR_MESSAGE);
            }
        return password;
    }
}
